on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  node:16

    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v3

        - name: Instala o node
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Instala as dependências
          run: npm ci

        - name: Executa o eslint
          run: npm run lint

        - name: Executa os testes
          run: npm test
          env:
            MYSQL_HOST: 'mysql'
            MYSQL_USER: 'root'
            MYSQL_PORT: 3306
            MYSQL_PASSWORD: 'password'

        - name: Gera relatório de testes
          uses: dorny/test-reporter@v1
          if: success() || failure()    # run this step even if previous step failed
          with:
            name: JEST Tests            # Name of the check run which will be created
            path: reports/jest-*.xml    # Path to test results
            reporter: jest-junit  