on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v3

        - name: Instala o node com a versão
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: instalando as dependências
          run: npm install

        - name: executando o lint para verificar se a erros
          run: npm run lint

        - name: executando os testes com Jest
          run: npm test